FROM intel/intel-extension-for-pytorch:2.1.10-xpu
USER root

RUN apt-get update -y || true; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget git python3-opencv && \
    rm -rf /var/lib/apt/lists/*

RUN pip install transformers>4.36.0 sentencepiece==0.1.99 shortuuid accelerate==0.21.0 peft==0.4.0 "pydantic<2,>=1" "markdown2[all]" scikit-learn==1.2.2 gradio==3.35.2 gradio_client==0.2.9 httpx==0.24.0 uvicorn fastapi einops==0.6.1 einops-exts==0.0.4 timm==0.6.13
RUN pip install neural-compressor intel-extension-for-transformers datasets
RUN pip install deepspeed tiktoken protobuf transformers_stream_generator
RUN pip install einops transformers_stream_generator
RUN pip install decord opencv-python git+https://github.com/facebookresearch/pytorchvideo.git@28fe037d212663c6a24f373b94cc5d478c8c1a1d
RUN pip install opencv-python-headless

WORKDIR /qllm
RUN apt-get update -y || true; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential cmake && \
    rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/intel/intel-extension-for-pytorch.git ipex-gpu; cd ipex-gpu; git checkout -b dev/QLLM origin/dev/QLLM; git submodule update --init --recursive

RUN apt install -y ca-certificates gnupg2 gpg-agent && apt-get clean && rm -rf  /var/lib/apt/lists/*
RUN wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
RUN echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
RUN apt update
RUN apt install -y zlib1g-dev python3-dev intel-basekit && \
    apt-get clean && \
    rm -rf  /var/lib/apt/lists/*
SHELL ["/bin/bash", "-c"]
RUN source /opt/intel/oneapi/setvars.sh; cd ipex-gpu; python setup.py install

COPY run-demo.py .
